version: '3'

services:
    app:
        container_name: app
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - database
        ports:
            - "8080:8080"
    database:
        container_name: database
        restart: always
        image: mysql:8
        volumes:
            - ./docker/runtime/mysql/lib:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: timetracker
