// timeTracker
export const SET_BREAKPOINT_START_TIME = 'SET_BREAKPOINT_START_TIME'
export const SET_BREAKPOINT_STOP_TIME = 'SET_BREAKPOINT_STOP_TIME'
export const CREATE_BREAKPOINT = 'CREATE_BREAKPOINT'
export const STOP_BREAKPOINT = 'STOP_BREAKPOINT'
export const REMOVE_BREAKPOINT = 'REMOVE_BREAKPOINT'
export const UPDATE_BREAKPOINT_TEXT = 'UPDATE_BREAKPOINT_TEXT'
export const UPDATE_UPLOAD_STATUS = 'UPDATE_UPLOAD_STATUS'

// settings
export const UPDATE_SETTING = 'UPDATE_SETTING'
