export const CREATE_BREAKPOINT = 'CREATE_BREAKPOINT'
export const STOP_BREAKPOINT = 'STOP_BREAKPOINT'
export const REMOVE_BREAKPOINT = 'REMOVE_BREAKPOINT'
export const UPDATE_BREAKPOINT_TEXT = 'UPDATE_BREAKPOINT_TEXT'
